# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import jsonfield.fields
import uuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', uuidfield.fields.UUIDField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('description', models.CharField(max_length=255)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
