# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields
import jsonfield.fields
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, max_length=22)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('description', models.CharField(max_length=255)),
                ('position', geoposition.fields.GeopositionField(default=b'51.1935462,6.4479122999999845', max_length=42)),
                ('data', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
