# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 08:43
from __future__ import unicode_literals

from django.db import migrations
import uuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='uuid',
            field=uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, unique=True),
        ),
    ]
