# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
        ('hive', '0002_auto_20151221_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='sensors',
            field=models.ManyToManyField(to='sensor.Sensor'),
        ),
    ]
