# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_hive_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
