# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 10:50
from __future__ import unicode_literals

from django.db import migrations
import uuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_auto_20151218_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='uuid',
            field=uuidfield.fields.UUIDField(blank=True, db_index=True, editable=False, max_length=32, unique=True),
        ),
    ]
