# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import jsonfield.fields
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, max_length=22)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('position', geoposition.fields.GeopositionField(blank=True, default=b'51.1935462,6.4479122999999845', max_length=42, null=True)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
