# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='version',
            field=models.IntegerField(choices=[(1, b'Basic Sensor Kit'), (2, b'v2 Wireless Device')], default=1),
        ),
    ]
