# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 10:33
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_box_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='position',
            field=geoposition.fields.GeopositionField(default=b'51.1935462,6.4479122999999845', max_length=42),
        ),
    ]
