# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields
import uuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_box_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default=b'51.1935462,6.4479122999999845', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='slug',
            field=uuidfield.fields.UUIDField(blank=True, db_index=True, editable=False, max_length=32, unique=True),
        ),
    ]
