# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, max_length=22)),
                ('name', models.CharField(choices=[(b'temperature_humidity', b'Temperature & Humidity'), (b'weight', b'Hive Weight'), (b'in_out_counter', b'In/Out Counter'), (b'video_stream', b'Video Stream')], db_index=True, max_length=128)),
                ('status', models.CharField(choices=[(b'unknown', b'Unknown'), (b'receiving', b'Receiving'), (b'disconnected', b'Disconnected')], db_index=True, max_length=128)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('boxes', models.ManyToManyField(to='box.Box')),
            ],
        ),
    ]
