# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='version',
            field=models.IntegerField(choices=[(1, b'Version 1 (Wired)'), (2, b'Version 2 (Wireless)')], db_index=True, default=1, max_length=4),
            preserve_default=False,
        ),
    ]
