# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='version',
            field=models.IntegerField(choices=[(1, b'Version 1 (Wired)'), (2, b'Version 2 (Wireless)')], db_index=True),
        ),
    ]
